config/routes.rb
Rails.application.routes.draw do
  get 'groups/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  # get  '/information',  to: 'informations#index'
  # get  '/category',  to: 'informations#category'
  


  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :self_introductions,  only: [:edit, :update, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :informations,        only: [:index, :show, :create, :destroy]
  resources :have_informations,   only: [:create, :destroy, :edit]
  resources :groups,              only: [:create, :destroy, :index, :show, :update]
  resources :tags,                only: [:create, :destroy]
  resources :favorites,           only: [:create, :destroy]
  resources :microposts,          only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    if logged_in?
      @self_introduction  = current_user.self_introduction
      @feed_items = current_user.feed.paginate(page: params[:page])
      @group = current_user.groups.build if logged_in?
      @user = current_user
      @groups2 = @user.groups
      group_ids = []
      @user.favorites.each{ |favorite_object| group_ids.push(favorite_object.group_id) }
      @groups3 = []
      group_ids.each{ |id| @groups3 << Group.find(id)}
    end
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_new_information.html.erb
<h1>新規タグの作成</h1>
<h2>(管理者専用)</h2> 
<br>
<div class="col-md-6 col-md-offset-3">
  <%= form_with(model: @information, url: informations_path, local: true) do |f| %>        
    <%= render 'shared/error_messages', object: f.object %>
    
    <%= f.label :category, "カテゴリー(played,console,contact,style)" %>
    <%= f.select :category, [ ["played","played"], ["console", "console"], ["contact", "contact" ] ,["style", "style"] ],
                            prompt: "カテゴリーを選択してください", class: "form-control" %>
  
    <%= f.label :content, "内容" %>
    <%= f.text_field :content, class: 'form-control' %>
    <%= f.submit "タグを作成！", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>本アプリ作成者へのお問合せ先</h1>
<p>
  【作成者指名】
  乾　福明（いぬい　としあき）
  　
  【メール】
  t.s.a.tahpkar@gmail.com

  【電話番号】
  080-6397-2236
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <% if current_user.admin? %>      
      <%= render 'new_information' %>
    <% end %>
  
    <aside class="col-md-5">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="self_introduction_form">
        <% if current_user.self_introduction.present? %>
          <div style="margin-left: 0%">         
            <h3>自己紹介</h3>
            <ol class="self_introductions">
              <%= render @self_introduction %>
              <%= link_to "自己紹介文編集", edit_self_introduction_path(current_user.self_introduction) %>              
            </ol>
          </div>
        <% else %>  
          <div style="margin-left: 0%">         
            <h3>自己紹介文作成</h3>      
          </div>
          <%= render 'shared/self_introduction_form' %>  
        <% end %>
      </section>      
      <section class="micropost_form">
        <div style="margin-left: 0%">         
          <h3>新規グループ作成</h3>      
        </div>        
        <%= render 'shared/group_form' %>
      </section>  
      <br>      
     <!--最近プレイ プレイした 持っている 連絡ツール 重視する項目 グループ-->
     <!--それぞれのcontent-->
     <!--それぞれの追加用ページリンク-->
      <div style="margin-left: 8%">         
        <h3>プレイヤー情報</h3>      
      </div>   
      <section>
        <%= render partial: 'informations/had_information', locals: { category: "recently", mode: "user",  owner: current_user } %>         
        <%= render partial: 'informations/had_information', locals: { category: "played"  , mode: "user",  owner: current_user } %> 
        <ul style="list-style: none;">
          <li><%= ("<br>").html_safe %></li>           
          <li><%= link_to "プレイしたゲームタグの追加と最近遊ぶゲームリスト編集"   ,   informations_path(cate: "played") %></li>
          <li><%= ("<br><br><br>").html_safe %></li>
        </ul>
            
        <%= render partial: 'informations/had_information', locals: { category: "console", mode: "user",  owner: current_user } %>
        <ul style="list-style: none;">
          <li><%= ("<br>").html_safe %></li> 
          <li><%= link_to "持っているゲーム機タグを追加" ,   informations_path(cate: "console") %></li>
          <li><%= ("<br><br><br>").html_safe %></li>  
        </ul>            
  
        <%= render partial: 'informations/had_information', locals: { category: "contact", mode: "user",  owner: current_user } %>
        <ul style="list-style: none;">
          <li><%= ("<br>").html_safe %></li>                     
          <li><%= link_to "通信ツールタグを追加"         ,   informations_path(cate: "contact") %></li>
          <li><%= ("<br><br><br>").html_safe %></li>           
        </ul>
  
        <%= render partial: 'informations/had_information', locals: { category: "style", mode: "user",  owner: current_user } %>
        <ul style="list-style: none;">
          <li><%= ("<br>").html_safe %></li>                     
          <li><%= link_to "プレイスタイルタグを追加"     ,    informations_path(cate: "style") %></li>
          <li><%= ("<br><br><br>").html_safe %></li>           
        </ul>
  
        <div style="margin-left: 8%">
          <h3>お気に入りのグループ</h3>      
        </div>
        <br>
        <% if @groups3.first.name.present? %>
          <ol class="microposts">
            <%= render partial: 'groups/group', collection: @groups3, as: "group" %>  
          </ol>
        <% else %>
          <ul style="list-style: none;">
            <li><%= ("<br>").html_safe %></li>                     
            <font size="3"><%= "お気に入りグループはありません" %></font>
          </ul>   
        <% end %>
        <br>
        <div style="margin-left: 8%">         
          <h3>作成したグループ</h3>      
        </div>
        <br>
        <% if @user.groups.first.name.present? %>
          <ol class="microposts">
            <%= render partial: 'groups/group', collection: @groups2, as: "group" %>             
          </ol>
        <% else %>
          <ul style="list-style: none;">
            <li><%= ("<br>").html_safe %></li>                     
            <font size="3"><%= "作成したグループはありません" %></font>
          </ul>   
        <% end %>
      </section>
      <div class="col-md-8">
        <!--<h3>フォローユーザー一覧</h3>-->
        <!--%= render 'shared/feed' %>-->
      </div>
  
      <% else %>
       <div class="center jumbotron">
        <h1>ゲームドへようこそ！</h1>
      
        <%= link_to "サインアップしてゲームドを始める！！", signup_path, class: "btn btn-lg btn-primary" %>
    </aside>
    <br>
    <br>
    <div><%= link_to "作成済みアカウントでログインする", login_path %></div>

        <% end %>
    </div>   