config/routes.rb
Rails.application.routes.draw do
  get 'groups/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  # get  '/information',  to: 'informations#index'
  # get  '/category',  to: 'informations#category'
  


  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :self_introductions,  only: [:edit, :update, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :informations,        only: [:index, :show, :create, :destroy]
  resources :have_informations,   only: [:create, :destroy, :edit]
  resources :groups,              only: [:create, :destroy, :index, :show, :update]
  resources :tags,                only: [:create, :destroy]
  resources :favorites,           only: [:create, :destroy]
  resources :microposts,          only: [:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% unless object == nil %>
  <% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <!--todo-->
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="self_introductions">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items,
                    params: { controller: :static_pages, action: :home } %>
<% end %>

app/views/shared/_group_form.html.erb
<%= form_with(model: @group, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :name, placeholder: "グループ名" %>
    <%= f.text_area  :explanation, placeholder: "グループの説明を記入..." %>
  </div>
  <%= f.submit "グループを作成する", class: "btn btn-primary" %>
  <br>
  <br>
  <div style="margin-left: 0%">         
    <h3>グループ画像</h3>      
  </div>  
  <span class="image">
    <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>    
  </span>  
<% end %>

<script type="text/javascript">
  $("#micropost_image").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file.");
      $("#micropost_image").val("");
    }
  });
</script>

app/views/shared/_micropost_form.html.erb
<%= form_with(model: @micropost, url: microposts_path , local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "投稿文を記入..." %>
  </div>
  <div><%= hidden_field_tag :user_id, current_user.id %></div>
  <div><%= hidden_field_tag :group_id, group.id %></div>
  <%= f.submit "投稿", class: "btn btn-primary" %>
  <span class="image">
    <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
  </span>
  
<% end %>

<script type="text/javascript">
  $("#micropost_image").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file.");
      $("#micropost_image").val("");
    }
  });
</script>

app/views/shared/_self_introduction_form.html.erb
<%= form_with(model: @self_introduction, url: {controller: 'self_introductions', action: 'create' }  ,local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
   <!--todo-->
   <%= f.text_area :content, placeholder: "自己紹介文を記入.." %>
  </div>
  <%= f.submit "投稿", class: "btn btn-primary" %>
    <!--    <span class="image">-->
    <!--      %= f.label :image, "プロフィール画像" %><br />-->
    <!--      %= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>-->
    <!--    </span>-->
<% end %>


<!--<script type="text/javascript">-->
<!--  $("#micropost_image").bind("change", function() {-->
<!--    var size_in_megabytes = this.files[0].size/1024/1024;-->
<!--    if (size_in_megabytes > 5) {-->
<!--      alert("Maximum file size is 5MB. Please choose a smaller file.");-->
<!--      $("#micropost_image").val("");-->
<!--    }-->
<!--  });-->
<!--</script>-->

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    フォロー中
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "プロフィールを表示", current_user %></span>