config/routes.rb
Rails.application.routes.draw do
  get 'groups/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  # get  '/information',  to: 'informations#index'
  # get  '/category',  to: 'informations#category'
  


  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :self_introductions,  only: [:edit, :update, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :informations,        only: [:index, :show, :create, :destroy]
  resources :have_informations,   only: [:create, :destroy, :edit]
  resources :groups,              only: [:create, :destroy, :index, :show, :update]
  resources :tags,                only: [:create, :destroy]
  resources :favorites,           only: [:create, :destroy]
  resources :microposts,          only: [:create, :destroy]
end

app/models/information.rb
class Information < ApplicationRecord
  has_many :tags,                 foreign_key: "information_id", 
                                  dependent:   :destroy
  has_many :groups, through: :tags
  has_many :have_informations,    foreign_key: "information_id",
                                  dependent:   :destroy  
  has_many :users, through: :have_informations    
  validates :category,  presence: true, length: { maximum: 50 }
  validates :content,  uniqueness: true, if: :category_played?
  validates :content,   presence: true, length: { maximum: 50 }

  def category_played?
    category == "played"
  end
end
                      

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  before_action :admin_user,     only: [:create, :destroy]

  def index
    if logged_in?
      @params = params[:cate]
      if @params == "played" || "console" || "contact" || "style"
        @informations = Information.where("category = ?", @params).paginate(page: params[:page])
      end
    end
  end
  
  def show
    @information = Information.find(params[:id])
    @user = current_user
    case params[:mode]
    when "user"
      @informations = @information.users.paginate(page: params[:page])
    when "group"
      @informations = @information.groups.paginate(page: params[:page])
    end  
  end 

  def create
    @information = Information.new(information_params)
    if @information.save
      flash[:info] = "新タグ保存"
    end
    redirect_to root_url
  end
  
  def destroy
    Information.find(params[:id]).destroy
    flash[:success] = "削除しました"
    redirect_to request.referrer || root_url
  end

private

  def information_params
    params.permit(:category, :content)
  end
  
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/views/informations/_had_information.html.erb
<ul style="list-style: none;">
  <% if mode == "user" %>
    <% case category %>
    <% when "recently" %>
    <% unless users_recently_have_info(current_user).any? %>
      <%= ("&nbsp;&nbsp;&nbsp;").html_safe %>    
      <li><font size="3"><%= "最近遊んだゲームが未登録！" %></font></li>
    <% else %>  
      <li style="text-decoration:underline"><font size="5"><%= "最近遊んでいるゲーム" %></font></li>
    <% end %>

    <!--ownerはgroupもしくはuserー-->
    <% when "played" %>
      <% unless owner.informations.where("category = ?", category).any? %>
        <%= ("&nbsp;&nbsp;&nbsp;").html_safe %>    
        <li><font size="3"><%= "これまで遊んだゲームが未登録！" %></font></li>         
      <% else %>     
        <li style="text-decoration:underline"><font size="5"><%= "これまでプレイしたゲーム" %></font></li>
      <% end %>
      
    <% when "console" %>
      <% unless owner.informations.where("category = ?", category).any? %>
        <%= ("&nbsp;&nbsp;&nbsp;").html_safe %>
        <li><font size="3"><%= "遊んでいるゲーム機未登録！" %></font></li>
        <li><%= ("<br>").html_safe %></li>   
      <% else %>  
        <li style="text-decoration:underline"><font size="5"><%= "遊んでいるゲーム機" %></font></li>
      <% end %> 
      
    <% when "contact" %>
      <% unless owner.informations.where("category = ?", category).any? %>
        <%= ("&nbsp;&nbsp;&nbsp;").html_safe %>    
        <li><font size="3"><%= "通信ツール未登録！" %></font></li>
      <% else %>  
        <li style="text-decoration:underline"><font size="5"><%= "使用する通信ツール" %></font></li>
      <% end %>
    <% when "style" %>
      <% unless owner.informations.where("category = ?", category).any? %>
        <li><font size="3"><%= "プレイスタイル未登録！" %></font></li>
      <% else %>  
        <li style="text-decoration:underline"><font size="5"><%= "プレイスタイル" %></font></li>
      <% end %>
    <% end %>
    <li><%= ("<br>").html_safe %></li>         
  <% end %>
  
  <% if category == "recently" %>
      <% users_recently_have_info(current_user).each do |have_info| %>
    <li>
      <% info = Information.find(have_info.information_id) %>
      <%= link_to "・#{info.content}", information_path(info, mode: "group") %>
    </li>
  
  <% end %>

  <%else %>
  
    <% owner.informations.where("category = ?", category).each do |info| %>

    <li>
      <%= link_to "・#{info.content}", information_path(info, mode: "group") %>      
    </li>

  <% end %>
  <li><%= ("<br>").html_safe %></li>        

<% end %>
<li><%= ("<br>").html_safe %></li>        

</ul>

app/views/informations/_have.html.erb
<%= form_with(model: current_user.have_informations.build, local: false) do |f| %>
  <div><%= hidden_field_tag :information_id, information.id %></div>
  <%= f.submit "タグを追加する", class: "btn btn-primary" %>
<% end %>

<!--%= form_with(model: current_user.have_informations.build, local: false) do |f| %>-->
<!--  <div>%= hidden_field_tag :information_id, @infomation.id %></div>-->
<!--  %= f.submit "追加する", class: "btn btn-primary" %>-->
<!--% end %>-->

app/views/informations/_have_form.html.erb
<div class="row">
  <div class="col-md-6">
    <div id="have_form">
      <% if current_user.have?(information) %>
        <!--%= render 'unhave' %>  -->
        <%= render partial: 'unhave', locals: { information: information } %>
      <% else %>
        <%= render partial: 'have', locals: { information: information } %>
      <% end %> 
    </div>
  </div>
</div>

 

app/views/informations/_information.html.erb
<div>
  <div><%= link_to information.content, information_path(information, mode: "group") %><div>
  <% if current_user.admin? %>
    | <%= link_to "削除", information, method: :delete,
                                  data: { confirm: "削除しますか?" } %>
  <% end %>      
  
  <% case mode %>
  <% when "user" %>
    <!--%= render 'have_form' if logged_in? %>-->
    <%= render partial: 'informations/have_form', locals: { information: information } if logged_in? %>
  <% when "group" %>
    <%= render partial: 'groups/tag_form', locals: { information: information } if logged_in? %>
  <% end %>
  <hr>  
</div>

app/views/informations/_unhave.html.erb
<%= form_with(model: current_user.have_informations.find_by(information_id: information.id),
            html: { method: :delete }, local: false) do |f| %>
  <div><%= hidden_field_tag :information_id, information.id %></div>
  <%= f.submit "タグを削除する", class: "btn btn-default" %>
<% end %>

<% if params[:cate] == "played" %>
  <% case current_users_have_information(information).recently %>
  <% when false %>
    <% unless recently_MAX? %>
      <%= link_to "最近遊んでいるゲームに登録", edit_have_information_path(id: information.id, key: "register") %>
    <% end %>  
  <% when true %>  
    <%= link_to "最近遊んでいるゲームから削除", edit_have_information_path(id: information.id, key: "remove") %> 
  <% end %>
<% end %>

<!--%= form_with(model: current_user.have_informations.find_by(information_id: @infomation.id),-->
<!--             html: { method: :delete }, local: false) do |f| %>-->
<!--   %= f.submit "削除する", class: "btn btn-default" %>-->
<!--% end %>-->

app/views/informations/category.html.erb
<div class=cate>
<% provide(:title, @params) %>
<% case @params %>
<% when "played"  %>
  <h1>プレイしたゲームを選択する</h1>
  <h3>今まで遊んだゲームを記録しよう！</h3>
  <h4>選んだゲームは遊んだことのあるゲームとしてプロフィールで表示されるぞ！</h4>
  
<% when "console" %>  
  <h1>ゲーム機を選択する</h1>
  <h3>普段使用しているゲーム機を選んで、プロフィールに表示させよう！</h3>
  

<% when "contact" %>  
  <h1>通信ツールを選択する</h1>
  <h3>他のユーザーと遊ぶ時に使う通信ツールを選んで、プロフィールに表示させよう！</h3>
  
<% when "style" %>  
  <h1>プレイヤーのスタイルを選択する</h1>
  <h3>自分のプレイスタイルを選んで、プロフィールに表示させよう！</h3>  

<% else %>    
  <%= render root_url  =%>  

<% end  %>  

<%= will_paginate %>

  <ul class="users">

    <%= render collection: @informations, partial: 'informations/information', locals: { mode: "user" } %>

  </ul>

<%= will_paginate %>

app/views/informations/index.html.erb
<div class="column">
  <% provide(:title, @params) %>
  <div>
    <% case @params %>
    <% when "played"  %>
      <h1>プレイしたゲームを選択する</h1>
      <h3>今まで遊んだゲームを記録しよう！</h3>
      <h4>選んだゲームは遊んだことのあるゲームとしてプロフィールで表示されるぞ！</h4>
      
    <% when "console" %>  
      <h1>ゲーム機を選択する</h1>
      <h3>普段使用しているゲーム機を選んで、プロフィールに表示させよう！</h3>

    <% when "contact" %>  
      <h1>通信ツールを選択する</h1>
      <h3>他のユーザーと遊ぶ時に使う通信ツールを選んで、プロフィールに表示させよう！</h3>
      
    <% when "style" %>  
      <h1>プレイヤーのスタイルを選択する</h1>
      <h3>自分のプレイスタイルを選んで、プロフィールに表示させよう！</h3>  
    
    <% else %>    
      <%= render root_url  =%>  
    <% end  %>  
  </div>
  <div>
    <%= will_paginate %>
    <ul class="users">
      <div class="column">
        <%= render collection: @informations, partial: 'information', locals: { mode: "user" } %>
      </div>
    </ul>
    <%= will_paginate %>
  </div>
</div>

app/views/informations/show.html.erb
<% provide(:title, @information.content) %>
<div class="inner">   
  <h3><%= @information.content %></h3>
  <br>
</div>
<%= will_paginate %>
<ul class="users">
  <% case params[:mode] %>
  <% when "user" %>
    <%= "#{@information.content}をタグ付けしたプレイヤー" %>
    <div><%= link_to "タグ付けされたグループを表示", information_path(@information, mode: "group") %><div>    
    <%= render partial: 'users/user',  collection: @informations, as: 'user' %>
  <% when "group" %>
    <%= "#{@information.content}にタグ付けされたグループ" %>
    <div><%= link_to "タグ付けしたユーザーを表示", information_path(@information, mode: "user") %><div>        
    <%= render partial: 'groups/group',  collection: @informations, as: 'group' %>
  <% end %>  
</ul>
<%= will_paginate %>