config/routes.rb
Rails.application.routes.draw do
  get 'groups/new'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  # get  '/information',  to: 'informations#index'
  # get  '/category',  to: 'informations#category'
  


  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :self_introductions,  only: [:edit, :update, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :informations,        only: [:index, :show, :create, :destroy]
  resources :have_informations,   only: [:create, :destroy, :edit]
  resources :groups,              only: [:create, :destroy, :index, :show, :update]
  resources :tags,                only: [:create, :destroy]
  resources :favorites,           only: [:create, :destroy]
  resources :microposts,          only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "ゲームド", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "プレイヤー", users_path %></li>
          <li><%= link_to "グループ", groups_path(cate: "none") %></li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              タグ <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "プレイしたゲーム"   ,   informations_path(cate: "played") %></li>
              <li><%= link_to "ゲーム機" ,   informations_path(cate: "console") %></li>          
              <li><%= link_to "通信ツール"         ,   informations_path(cate: "contact") %></li>
              <li><%= link_to "プレイスタイル"     ,    informations_path(cate: "style") %></li>          
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "マイプロフィール", current_user %></li>
              <li><%= link_to "ユーザーアカウント編集", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>          
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%="Gamed_app" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>